name: Validate & Release
on:
  push:
    branches:
      - '**'

jobs:
  check:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check -recursive -diff=true modules
        # continue-on-error: true

      # semver version tag
      - name: Bump version and push tag
        id: semver
        uses: mathieudutour/github-tag-action@v4.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: "master"